version: "3.7"

services:
  camapi:
    container_name: niftified.api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: http://+:5050
    expose:
      - "5050"
    ports:
      - "5050:5050"

  camclient:
    container_name: niftified.client
    build:
      context: ./Client
      dockerfile: Dockerfile
    restart: always
    expose:
      - "5151"
    ports:
      - "5151:5151"

# Remember to start the network before running this file:
# $ docker network create mydockernet
#
# Then you can start each of the docker-compose.yml files like this:
# $ docker-compose -f project_one/docker-compose.yml up -d
# $ docker-compose -f project_two/docker-compose.yml up -d
networks:
  default:
    external:
      name: mydockernet
