version: "3.7"

services:
  niftyapi:
    container_name: niftified.api
    build:
      context: ./
      dockerfile: Dockerfile

    restart: always

    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:5050"
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft: "Information"
      Logging__LogLevel__Niftified: "Debug"
      AppSettings__StoredFilesPath: "wwwroot/files"
      ConnectionStrings__DefaultConnection: "Data Source=./db/NiftifiedDatabase.db"
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PAYMENT_TYPES: ${STRIPE_PAYMENT_TYPES}
      STRIPE_DOMAIN: ${STRIPE_DOMAIN}

    expose:
      - "5050"

    ports:
      - "5050:5050"

    volumes:
      - niftyapi-db:/app/db
      - niftyapi-files:/app/wwwroot/files

  niftyclient:
    container_name: niftified.client
    build:
      context: ./Client
      dockerfile: Dockerfile

    restart: always

    expose:
      - "5151"

    ports:
      - "5151:5151"

volumes:
  niftyapi-db:
    driver: local
  niftyapi-files:
    driver: local

# Remember to start the network before running this file:
# $ docker network create mydockernet
#
# Then you can start each of the docker-compose.yml files like this:
# $ docker-compose -f project_one/docker-compose.yml up -d
# $ docker-compose -f project_two/docker-compose.yml up -d
networks:
  default:
    external:
      name: mydockernet
